import { enableProdMode, importProvidersFrom } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { provideRouter, RouteReuseStrategy } from '@angular/router';
import { IonicModule, IonicRouteStrategy } from '@ionic/angular';
import { addIcons } from 'ionicons';
import {
  addCircle,
  addOutline,
  alertOutline,
  arrowBackOutline,
  arrowDownCircleOutline,
  arrowUpCircleOutline,
  arrowUpOutline,
  barChart,
  calendarOutline,
  car,
  carOutline,
  cash,
  cashOutline,
  checkmarkOutline,
  chevronBackOutline,
  chevronDownOutline,
  chevronForwardOutline,
  downloadOutline,
  ellipsisHorizontal,
  eyeOffOutline,
  eyeOutline,
  filterOutline,
  gameController,
  heart,
  helpCircleOutline,
  home,
  homeOutline,
  informationOutline,
  list,
  listOutline,
  locateOutline,
  lockClosedOutline,
  logOutOutline,
  mailOutline,
  menuOutline,
  notificationsOutline,
  person,
  personOutline,
  pricetagOutline,
  removeCircle,
  restaurant,
  restaurantOutline,
  searchOutline,
  settingsOutline,
  shieldCheckmark,
  wallet,
  walletOutline,
  warningOutline
} from 'ionicons/icons';
import { AppComponent } from './app/app.component';
import { routes } from './app/app.routes';

addIcons({
  'add-circle': addCircle,
  'add-outline': addOutline,
  'alert-outline': alertOutline,
  'arrow-back-outline': arrowBackOutline,
  'arrow-down-circle-outline': arrowDownCircleOutline,
  'arrow-up-circle-outline': arrowUpCircleOutline,
  'arrow-up-outline': arrowUpOutline,
  'bar-chart': barChart,
  'calendar-outline': calendarOutline,
  car,
  'car-outline': carOutline,
  cash,
  'cash-outline': cashOutline,
  'checkmark-outline': checkmarkOutline,
  'chevron-back-outline': chevronBackOutline,
  'chevron-down-outline': chevronDownOutline,
  'chevron-forward-outline': chevronForwardOutline,
  'download-outline': downloadOutline,
  'ellipsis-horizontal': ellipsisHorizontal,
  'eye-off-outline': eyeOffOutline,
  'eye-outline': eyeOutline,
  'filter-outline': filterOutline,
  'game-controller': gameController,
  heart,
  'help-circle-outline': helpCircleOutline,
  home,
  'home-outline': homeOutline,
  'information-outline': informationOutline,
  list,
  'list-outline': listOutline,
  'locate-outline': locateOutline,
  'lock-closed-outline': lockClosedOutline,
  'log-out-outline': logOutOutline,
  'mail-outline': mailOutline,
  'menu-outline': menuOutline,
  'notifications-outline': notificationsOutline,
  person,
  'person-outline': personOutline,
  'pricetag-outline': pricetagOutline,
  'remove-circle': removeCircle,
  restaurant,
  'restaurant-outline': restaurantOutline,
  'search-outline': searchOutline,
  'settings-outline': settingsOutline,
  'shield-checkmark': shieldCheckmark,
  wallet,
  'wallet-outline': walletOutline,
  'warning-outline': warningOutline
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideRouter(routes),
    importProvidersFrom(IonicModule.forRoot({}))
  ]
}).catch(err => console.error(err));
